eMenu/menu/urls.py
__author__ = 'pstepnowski'

from django.conf.urls import patterns, url

urlpatterns = patterns('eMenu.menu.views',
    url(r'^$', 'menu_list', name='menu_list'),
    url(r'^(?P<menu_id>\d{1,12})/(?P<menu_slug>[\w-]+)/$', 'view_menu', name='view_menu'),
    url(r'reportbug/$', 'report_bug', name='report_bug'),
)

eMenu/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': ('eMenu',)}),
    url(r'^', include('eMenu.menu.urls', namespace='menu')),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^media/(?P<path>.*)$', 'serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )


eMenu/menu/models.py
# -*- coding: utf-8 -*-
__author__ = 'pstepnowski'

from django.db import models
from django.utils.functional import cached_property

from eMenu.utils.fields import ImageField
from eMenu.utils.text import slugify

MENU_CATEGORIES = (
    ('snacks', 'Przekąski'),
    ('soups', 'Zupy'),
    ('main_dish', 'Główne danie'),
    ('desserts', 'Desery'),
    ('cold_drinks', 'Napoje'),
)


class Meal(models.Model):
    name = models.CharField('Nazwa', max_length=255, unique=True)
    description = models.TextField('Opis')
    image = ImageField(
        verbose_name='Zdjęcie', min_size=(230, 160), max_size=(1024, 1024),
        max_filesize=512*1024, blank=True, default='', upload_to='menu/meals')
    category = models.CharField('Kategoria', max_length=63, choices=MENU_CATEGORIES)

    class Meta:
        verbose_name = 'Danie'
        verbose_name_plural = 'Dania'

    def __unicode__(self):
        return self.name


class Menu(models.Model):
    name = models.CharField('Nazwa', max_length=255,)
    meals = models.ManyToManyField(Meal, verbose_name='meals', through='MenusMeals')
    slug = models.SlugField('slug', max_length=255, blank=True, editable=False)

    class Meta:
        verbose_name = 'Menu'
        verbose_name_plural = 'Menu'
        ordering = ['-id']

    def __unicode__(self):
        return self.name

    def clean(self):
        if not self.slug:
            self.slug = slugify(self.name)
        return super(Menu, self).clean()

    @models.permalink
    def get_absolute_url(self):
        return ('menu:view_menu', (), {
            'menu_id': self.pk, 'menu_slug': self.slug})

    @cached_property
    def meals_count(self):
        return self.meals.count()


class MenusMeals(models.Model):
    menu = models.ForeignKey(Menu, verbose_name='menu')
    meal = models.ForeignKey(Meal, verbose_name='meal')

    class Meta:
        verbose_name = 'Danie'
        verbose_name_plural = 'Dania'
        unique_together = ('menu', 'meal',)

    def __unicode__(self):
        return u'%(meal)s w %(menu)s' % {
            'meal': unicode(self.meal), 'menu': unicode(self.menu)}


class UserMessage(models.Model):
    email = models.EmailField('E-mail', blank=True)
    description = models.TextField('Opis')
    created = models.DateTimeField('Zgłoszono', auto_now_add=True)

    class Meta:
        verbose_name = 'Zgłoszony bład'
        verbose_name_plural = 'Zgłoszone błędy'

    def __unicode__(self):
        return u'Zgłoszenie #%d' % (self.pk,)

eMenu/menu/forms.py
# -*- coding: utf-8 -*-
__author__ = 'pstepnowski'

from django import forms

from captcha.fields import CaptchaField

from .models import UserMessage

MENU_SORT_OPTIONS = (
    ('', '---'),
    ('-name', 'Nazwa - malejąco'),
    ('name', 'Nazwa - rosnąco'),
    ('-meals_count', 'Liczba dań - malejąco'),
    ('meals_count', 'Liczba dań - rosnąco'),
)


class MenuSortForm(forms.Form):
    sort_option = forms.ChoiceField(choices=MENU_SORT_OPTIONS, required=False, label='Sortuj wg')


class ReportBugForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = UserMessage
        fields = ('email', 'description',)

eMenu/menu/views.py
# -*- coding: utf-8 -*-
__author__ = 'pstepnowski'

from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from django.contrib import messages

from eMenu.utils.pagination import page_or_404

from .models import Menu
from .forms import MenuSortForm, ReportBugForm


def menu_list(request):
    qs = Menu.objects.annotate(meals_count=Count('meals')).filter(meals_count__gt=0)

    form = MenuSortForm(request.GET or None)
    if form.is_valid():
        sort_option = form.cleaned_data.get('sort_option')
        if sort_option:
            qs = qs.order_by(sort_option)

    page = page_or_404(request, qs, 6)
    return render(request, 'menu/menu_list.html', {'page': page, 'form': form})


def view_menu(request, menu_id, menu_slug):
    menu = get_object_or_404(Menu, pk=menu_id, slug=menu_slug)

    return render(request, 'menu/view_menu.html', {'menu': menu})


def report_bug(request):
    form = ReportBugForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.add_message(request, messages.INFO, 'Formularz został wysłany.')
        return redirect('menu:menu_list')

    return render(request, 'menu/report_bug.html', {'form': form})

eMenu/menu/templates/menu/menu_list.html
{% extends "base_site.html" %}
{% load url from future %}
{% load i18n static l10n query_string %}

{% block page_title %}Zestawy dań{% endblock %}

{% block content %}
    <div class="col-xs-12 col-sm-9">
        <div class="jumbotron">
            <h1>Lista kart menu</h1>
            <p>Zawsze najlepsze posiłki, smacznego :)</p>
        </div>
        {% include "messages.html" %}
        <div style="margin-left: 15px;">
            SORTUJ WG:
            <form method="get" action=".">
                {% include "forms/fields/select.html" with field=form.sort_option classes="autosubmit" %}
            </form>
        </div>
        {% for menu in page.object_list %}
            <div class="col-6 col-sm-6 col-lg-4">
                <h2>{{ menu.name}}</h2>
                <p>Ilość posiłków na karcie: {{ menu.meals_count }}</p>
                <p><a class="btn btn-default" href="{{ menu.get_absolute_url }}" role="button">Wyświetl kartę »</a>
                </p>
            </div>
        {% empty %}
            <div>Brak kart menu do wyświetlenia</div>
        {% endfor %}
    </div>

    <div class="col-xs-12 col-sm-9">
        <ul class="pager" style="text-align: left;">
            <li {% if not page.has_previous %}class="disabled"{% endif %}><a href="?{% query_string "page" page=page.previous_page_number %}">Poprzedni</a></li>
            <li {% if not page.has_next %}class="disabled"{% endif %}><a href="?{% query_string "page" page=page.next_page_number %}">Następny</a></li>
        </ul>
    </div>
{% endblock %}

eMenu/menu/templates/menu/report_bug.html
{% extends "base_site.html" %}
{% load url from future %}
{% load i18n static l10n query_string %}

{% block page_title %}Formularz zgłaszania błędów{% endblock %}

{% block content %}
    <div class="col-xs-12 col-sm-9">
        <div class="jumbotron">
            <h1>Formularz zgłaszania błędów</h1>
        </div>
        <form method="post" action="." >{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" />
        </form>
    </div>
{% endblock %}

eMenu/menu/templates/menu/view_menu.html
{% extends "base_site.html" %}
{% load url from future %}
{% load i18n static l10n thumbnail %}

{% block page_title %}Zestawy dań{% endblock %}

{% block content %}
    <div class="col-xs-12 col-sm-9">
        <div class="jumbotron">
            <h1>{{ menu.name }}</h1>
        </div>
        <div>Dania</div>
        {% for meal in menu.meals.all %}
            <div class="col-6 col-sm-6 col-lg-4">
                <h3>{{ meal.name }}</h3>
                <div style="width: 140px;height: 100px;">
                {% thumbnail meal.image "140x100" crop="50% 50%" as t %}
                    <p class="image"><img src="{{ t.url }}" alt="{{ meal.name|lower }}"></p>
                {% endthumbnail %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

eMenu/templates/base_site.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">{% load static i18n %} {% load url from future %}
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">{% block page_styles %}
    <link rel="stylesheet" type="text/css" href="{% static " eMenu/styles/screen.css " %}?1">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">{% endblock %} {% block page_head %}{% endblock %}

    <meta name="description" content="{% block page_description %}{% endblock %}">
    <meta name="keywords" content="{% block page_keywords %}{% endblock %}">

    <title>{% block page_title %}{% endblock %} - {{ site.name }}</title>
</head>

<body>
    {% include "nav.html" %}
    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
            {% block content %}{% endblock %}
        </div>
        <hr>
        {% include "footer.html" %}
    </div>

    {% block page_scripts %}
    <script type="text/javascript" src="{% static "eMenu/scripts/jquery-1.11.0.min.js" %}"></script>
    <script type="text/javascript" src="{% static "eMenu/scripts/main.js" %}"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    {% endblock %}
</body>

</html>

eMenu/templates/content.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

eMenu/templates/footer.html
<footer>
    <p>© eMenu 2014</p>
</footer>

eMenu/templates/menu.html
{% load url from future %}

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">eMenu</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Lista dań</a></li>
            <li><a href="#about">Formularz zgłaszania błędów</a></li>
            <li><a href="#contact">Kontakt</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

eMenu/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
{% endif %}

eMenu/templates/nav.html
{% load url from future %}
{% load active from navigation %}

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">eMenu</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="{% active '/' %}"><a href="{% url "menu:menu_list" %}">Lista kart menu</a></li>
                <li class="{% active '/reportbug/' %}"><a href="{% url "menu:report_bug" %}">Formularz zgłaszania błędów</a></li>
            </ul>
        </div>
    </div>
</div>

eMenu/templates/test.html
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Off Canvas Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style type="text/css"></style></head>

  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Hello, world!</h1>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
          </div>
          <div class="row">
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
            <a href="#" class="list-group-item active">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>© Company 2014</p>
      </footer>

    </div><!--/.container-->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="offcanvas.js"></script>


</body></html>

eMenu/utils/templates/forms/fields/select.html
{% load l10n %}
<select id="{{ id }}" onchange="{{ onchange }}" name="{{ field.html_name }}"{% if classes or field.errors %}class="{{ classes }}{% if field.errors %} error{% endif %}"{% endif %}>
    {% for value, label in field.field.choices %}
        <option value="{{ value|unlocalize }}"{% if value|stringformat:"s" == field.value|stringformat:"s" %} selected="selected"{% endif %}>{{ label }}</option>
    {% endfor %}
</select>